### ISSUE TITLE
【Lea】月々の入金がされていない

### ISSUE THREAD

**Issue by miohoshino** [youlib-Inc/youlib-community#63]
## 事象

Leaで野菜販売をしていますが、4月以降、毎月25日に行われるはずの入金がない状態です。

また、入金した旨の通知メールが3月までは来ていましたが4月は来ていません。ただし月ごとの入金メールは特に必要ではないのでメールは今後も無くていいです。

**Comment by yusei-hyodo** [comment]
対応しました。
