### ISSUE TITLE
【Lea】

### ISSUE THREAD

**Issue by miohoshino** [youlib-Inc/youlib-community#66]
## 提案・要望

月々の振込額明細がわかる機能がほしい

## 背景

月々の帳簿付けの際、その月の売り上げ明細は現在の売り上げページで見られるのですが、実際に振り込まれた際の摘要がわからないため、手数料等を後から計算しなおす必要があります。
どこかでその月の売り上げ額・手数料・振り込まれる金額がわかるとうれしいです。

**Comment by yusei-hyodo** [comment]
了解です！
8月下旬のアップデート対象に入れときます。
