### ISSUE TITLE
領収書・納品書の発行について【Lea】

### ISSUE THREAD

**Issue by narugen** [youlib-Inc/youlib-community#67]
## 提案・要望

領収書・納品書をお客様が自分で発行できる機能が欲しいです。

## 背景

企業がお客様にもいるので、納品書・領収書の要望が多いため。

## 関連

手間を減らしたいので、発行を自動でしたい。
できれば再度発行する際も、再発行が表示されるようにしたい。

**Comment by yusei-hyodo** [comment]
お問い合わせありがとうございます。

領収書発行に関しましては、リリース時より自動発行処理を導入しております。
注文処理が受取完了に移動すると、注文詳細ページに「領収書」ボタンが自動的に表示されます。

ドキュメントページをアップデートしたので、よければこちらをご確認ください！
[https://docs.lea-market.com/help-faq/#%E9%A0%98%E5%8F%8E%E6%9B%B8%E7%99%BA%E8%A1%8C%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6](url)
